services:
  - type: web
    name: aldren-gacute-portfolio
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
